"""create user collections and items tables

Revision ID: 842e9b9c7df3
Revises: 99fe09eae9eb
Create Date: 2026-09-05 16:26:17.256608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842e9b9c7df3'
down_revision: Union[str, Sequence[str], None] = '99fe09eae9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_collections_user_id'), 'user_collections', ['user_id'], unique=True)
    op.create_table('user_collection_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['user_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_collection_items_card_id'), 'user_collection_items', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_collection_items_collection_id'), 'user_collection_items', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_collection_items_collection_id'), table_name='user_collection_items')
    op.drop_index(op.f('ix_user_collection_items_card_id'), table_name='user_collection_items')
    op.drop_table('user_collection_items')
    op.drop_index(op.f('ix_user_collections_user_id'), table_name='user_collections')
    op.drop_table('user_collections')
    # ### end Alembic commands ###
