"""create initial tables

Revision ID: b7cb4a9a3db0
Revises: 
Create Date: 2026-09-03 22:24:53.718224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7cb4a9a3db0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('series', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('total_cards', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_external_id'), 'sets', ['external_id'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=100), nullable=False),
    sa.Column('supertype', sa.String(length=50), nullable=False),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('national_dex_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_external_id'), 'cards', ['external_id'], unique=True)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_national_dex_number'), 'cards', ['national_dex_number'], unique=False)
    op.create_index(op.f('ix_cards_rarity'), 'cards', ['rarity'], unique=False)
    op.create_index(op.f('ix_cards_set_id'), 'cards', ['set_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_market', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_snapshot_card_date', 'price_snapshots', ['card_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_captured_at'), 'price_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_card_id'), 'price_snapshots', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_snapshots_card_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_captured_at'), table_name='price_snapshots')
    op.drop_index('idx_price_snapshot_card_date', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_cards_set_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_rarity'), table_name='cards')
    op.drop_index(op.f('ix_cards_national_dex_number'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_external_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_sets_external_id'), table_name='sets')
    op.drop_table('sets')
    # ### end Alembic commands ###
